### ISSUE TITLE
Hello，协议问题：请查看下163邮箱

### ISSUE THREAD

**Issue by YoKeyword** [gpfduoduo/FragmentUtil#1]
Hello，协议问题：请看下163邮箱

**Comment by gpfduoduo** [comment]
@YoKeyword 
已收到并答复……对您造成的麻烦，请谅解……我喜欢看别人写的代码，也喜欢跟着写……自己写一遍，理解和看完全不是一个层次……

非常抱歉，我会进行处理……

**Comment by YoKeyword** [comment]
@gpfduoduo 随时交流～   :)
